telegram_data:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: lilyMK
      dbname: Telegram_data
      port: 5432
      schema: public
      threads: 4
